### PR TITLE
fix: bypass ni sequelize connection on training env

### PR DESCRIPTION
**Pull request by Yakitrak**
## Describe your changes

Ticket: https://pins-ds.atlassian.net/browse/APPLICS-479

PR uses a mock sequelize connection if using training environment (determined by BACK_OFFICE_INTEGRATION_GET_APPLICATIONS  feature flag being set as 'BO'), which would bypass the NI connection errors that occurred because training environment cannot access NI. This approach was chosen over a memory DB as it requires no new dependancies or more memory, whilst still ensuring everything is built correctly

## Type of change 🧩

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update
- [ ] Other (please explain in the description section above)

## Checklist before requesting a review

- [x] I have performed a self-review of my own code
- [x] I have double checked this work does not include any hardcoded secrets or passwords
- [x] I have made corresponding changes to the documentation
- [x] I have provided details on how I have tested my code
- [x] I have referenced the ticket number above
- [x] I have provided a description of the ticket
- [x] I have included unit tests to cover any testable code changes

### CODE REVIEW

**Review by beejjacobs — APPROVED** [review]
Seems a good method, that way as environments move over to BO only they won't try and connect to NI either.

I might suggest pulling out of some the logic into a small util function, that way the sequelize instance could be returned and be `const` here. Given this code could be removed once NI is retired though, not worth doing!

**Comment by Yakitrak** [comment]
> Seems a good method, that way as environments move over to BO only they won't try and connect to NI either.
> 
> I might suggest pulling out of some the logic into a small util function, that way the sequelize instance could be returned and be `const` here. Given this code could be removed once NI is retired though, not worth doing!

Thanks! And yeah I considered splitting it out as well but because we will likely remove it soon, I kept the change as small as possible.

**Pull request merged**
