### PR TITLE
Added new common volume package to docker-compose to correct build issue on Windows machines

### PR DESCRIPTION
**Pull request by johnmoscrip**
## Added new common volume package to docker-compose to correct build issue on Windows machines

Update to docker-compose.yml to include new file reference

## Useful information to review or test

Prior to this change the application service solution build would fail with a "Cannot find module '@pins/common/src/utils/redis'" error when attempting to do a "npm run dev".  Including a reference to the module in docker-compose corrected this error.  The fix has been confirmed by myself and Ben Jacobs.  There is nothing to test on the front end for this fix.  There is no ticket for this issue.

## Type of change 🧩

- [X] Bug fix (non-breaking change which fixes an issue)

## Checklist before requesting a review

- [X] I have performed a self-review of my own code
- [X] I have double checked this work does not include any hardcoded secrets or passwords

### CODE REVIEW

**Review by Yakitrak — CHANGES_REQUESTED** [review]
Looks out of date from main as its got 25 file changes (instead of just the docker file).

**Comment by johnmoscrip** [comment]
> Looks out of date from main as its got 25 file changes (instead of just the docker file).

Yep, that's odd.  Let me check.

**Pull request merged**
