### PR TITLE
feat: c4 diagrams deployment gh action update

### PR DESCRIPTION
**Pull request by Yakitrak**
## Describe your changes

C4 diagrams will now be deployed on GH pages using GH actions.

Ticket: https://pins-ds.atlassian.net/browse/ASB-2453

Deployed link: https://planning-inspectorate.github.io/applications-service/master/

## Type of change 🧩

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation update
- [ ] Other (please explain in the description section above)

## Checklist before requesting a review

- [x] I have performed a self-review of my own code
- [x] I have double checked this work does not include any hardcoded secrets or passwords
- [x] I have made corresponding changes to the documentation
- [x] I have provided details on how I have tested my code
- [x] I have referenced the ticket number above
- [x] I have provided a description of the ticket
- [x] I have included unit tests to cover any testable code changes

### CODE REVIEW

**Comment by PeterBridgerKC** [comment]
In terms of functionality this looks good

However I think it's also worth using this opportunity to update `README.md` to sign post that this documentation exists. My first thought would be in the same area that we reference using `npm run c4` to view this locally, it's a great chance to people to view it without needing to checkout the repository

**Review by Philip-Philippou1 — APPROVED** [review]

**Pull request merged**
