### PR TITLE
fix: backoffice sub node_modules

### PR DESCRIPTION
**Pull request by Yakitrak**
## Describe your changes

Merging https://github.com/Planning-Inspectorate/applications-service/pull/863 has introduced an issue on the build pipeline which should be fixed by removing the below stage.

## Type of change 🧩

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update
- [ ] Other (please explain in the description section above)

## Checklist before requesting a review

- [x] I have performed a self-review of my own code
- [x] I have double checked this work does not include any hardcoded secrets or passwords
- [x] I have made corresponding changes to the documentation
- [x] I have provided details on how I have tested my code
- [x] I have referenced the ticket number above
- [x] I have provided a description of the ticket
- [x] I have included unit tests to cover any testable code changes

### CODE REVIEW

**Review by JamesP-KC — APPROVED** [review]
Thanks for fixing 👍

**Comment by Yakitrak** [comment]
> Thanks for fixing 👍

Its your fix - thank you for the help!

**Pull request merged**
