### PR TITLE
ASB-269 change layout and styling

### PR DESCRIPTION
**Pull request by pk2453**

### CODE REVIEW

**Comment by pk2453** [comment]
Slight change required in internal layout of about-your-application page which can be done during changing the layout of documents displayed. Other pages header and banner is also changed.

**Comment by cpcundill** [comment]
Checking out locally to take a look at the visual changes

**Review by cpcundill — CHANGES_REQUESTED** [review]
Have scheduled a meeting at 3pm with Naomi and Aqib to confirm whether we should be going with the bigger width.

**Review by cpcundill — CHANGES_REQUESTED** [review]
Still not quite what I'd expected and tried to explain earlier.  I've mocked up some changes locally for us to discuss on Monday.

**Comment by cpcundill** [comment]
Will be raising a new approach with a revised approach

**Pull request closed without merging**
