### PR TITLE
Fix/applics 739 consolidate package versions

### PR DESCRIPTION
**Pull request by edpackard-work**
## Describe your changes

* remove unnecessary non-root package-lock.json files from workspaces
* consolidate packages and versions in root package.json file
* convert package versions in workspace package.json files to use "*" (they will obtain version from root package.json)
* use `npm ci --workspaces --if-present` in Dockerfiles: this tells npm to only install dependencies that are required for that build (i.e. the workspaces that have been copied in), thus reducing total installation size
* update README to include instructions on installing dependencies

Other small changes:
* update legacy e2e NI db seed data - a registration period had closed causing tests to fail
* fix a small bug that was preventing a translation from rendering in forms-web-app, spotted while manually testing this ticket

https://pins-ds.atlassian.net.mcas.ms/jira/software/c/projects/APPLICS/boards/242?selectedIssue=APPLICS-739

I have tested this locally and have built/deployed the repo to dev for manual testing. In particular, I checked that the BO subscriber functions were working as expected.

## Useful information to review or test

To test locally, ensure you remove existing node_modules (npx npkill is useful) and run npm ci from root to install dependencies.

## Type of change 🧩

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update
- [ ] Other (please explain in the description section above)

## Checklist before requesting a review

- [x] I have performed a self-review of my own code
- [x] I have double checked this work does not include any hardcoded secrets or passwords
- [x] I have made corresponding changes to the documentation
- [x] I have provided details on how I have tested my code
- [x] I have referenced the ticket number above
- [x] I have provided a description of the ticket
- [ ] I have included unit tests to cover any testable code changes

### CODE REVIEW

**Review by BenSurgisonPINS — APPROVED** [review]
lgtm

**Review by DavidJWhiteDev — APPROVED** [review]
and lgtm

**Pull request merged**
