### PR TITLE
feat: welsh translation - api changes for section 51 advice (APPLICS-223)

### PR DESCRIPTION
**Pull request by BenSurgisonPINS**
## Describe your changes

Welsh translation - API changes for Section 51 Advice

Ticket: https://pins-ds.atlassian.net/browse/APPLICS-223

PR adds welsh title, welsh advice given and welsh enquiry detail fields to prisma schema and API.

I used Swagger to test the API.

## Type of change 🧩

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update
- [ ] Other (please explain in the description section above)

## Checklist before requesting a review

- [x] I have performed a self-review of my own code
- [x] I have double checked this work does not include any hardcoded secrets or passwords
- [ ] I have made corresponding changes to the documentation
- [x] I have provided details on how I have tested my code
- [x] I have referenced the ticket number above
- [x] I have provided a description of the ticket
- [ ] I have included unit tests to cover any testable code changes

### CODE REVIEW

**Comment by BenSurgisonPINS** [comment]
> The changes look good but wondering if this PR should include changes to consume new fields in the functions package? I don't see it on the AC here but it was the case for the other ticket I did so just double checking.

I've added changes to the back-office-subscriber functions as suggested

**Review by Yakitrak — APPROVED** [review]
LGTM

**Pull request merged**
