### PR TITLE
Task/ASB 426 merge release to main

### PR DESCRIPTION
**Pull request by Philip-Philippou1**
Merge release branch release/1.x into main branch.

Steps so far:
- Merge branch created from release/1.x
- Main merged into merge branch
- Conflicts resolved
- This PR created to merge the merge branch back into main.

### CODE REVIEW

**Comment by andylangridge** [comment]
You can add `junit.xml` to `.gitignore`! I don't think we want to be committing those files as they get auto-generated on test runs.

**Comment by andylangridge** [comment]
The API pipeline has a linting issue:
```
/__tests__/unit/lib/notify.test.js
  7:16  error  `.../../../src/lib/config` import should occur before import of `../../../src/lib/notify`  import/order

/src/controllers/documents.js
  69:80  warning  Unexpected unnamed function  func-names
```

You can either fix these, or just stop the pipeline running tests (there is a flag in the build pipeline step). The PR I raised addresses linting anyway, so I can sort that out in my branch if you like. I have turned off running tests in the pipeline for now anyway since I've stopped them from running in the container, and will run them on the agent in their own step (which will be the next thing I work on after the linting PR is merged).

**Comment by Philip-Philippou1** [comment]
> You can add `junit.xml` to `.gitignore`! I don't think we want to be committing those files as they get auto-generated on test runs.

Removed file, it was in .gitignore so not sure why it sneaked in.

**Comment by Philip-Philippou1** [comment]
> 

I'll run the test manually for now so we can get this moving.

**Review by andylangridge — APPROVED** [review]

**Pull request merged**
