### PR TITLE
ASB 332 - Feature/contact email

### PR DESCRIPTION
**Pull request by Xfarya**
added contact email sections - replacing applications reference appData.ProjectEmailAddress

changed order to follow prototype

added phone number tel link

### CODE REVIEW

**Review by christopher-semmens — COMMENTED** [review]
Looks like the files that compile on build have made they way onto the PR:
- `packages/forms-web-app/src/public/javascripts/cookiePreferences.bundle.js`
- `packages/forms-web-app/src/public/javascripts/index.bundle.js`
- `packages/forms-web-app/src/public/stylesheets/main.css`
Might be worth keeping them off the PRs if they are not related to the work.

**Review by christopher-semmens — CHANGES_REQUESTED** [review]
Looks like the build is failing due to not passing the lint tests.

**Review by christopher-semmens — CHANGES_REQUESTED** [review]
`main.css` is causing a merge conflict.

**Review by Philip-Philippou1 — COMMENTED** [review]
I think those files (main.css, index.bundle.js, cookiePreferences.bundle.js) have been deleted, we still need them, they just need to be reverted to the original from main branch.

**Pull request closed without merging**
