### PR TITLE
Fix/applics 826 hard coded creds

### PR DESCRIPTION
**Pull request by johnmoscrip**
## Describe your changes

[https://pins-ds.atlassian.net/browse/APPLICS-826](https://pins-ds.atlassian.net/browse/APPLICS-826)

Removed hard coded ENCRYPTION_SECRET_KEY value and replaced with an env file.   Updated documentation.  

Tested locally. 

## Useful information to review or test

This change is related to the encryption/decryption functionality when signing up with an email address for updates on projects.  E.g. https://applications-service-test.planninginspectorate.gov.uk/projects/BC0910150/get-updates/start.  Testing shoudl be conducted for this functionality.

## Type of change 🧩

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update
- [ ] Other (please explain in the description section above)

## Checklist before requesting a review

- [X] I have performed a self-review of my own code
- [X] I have double checked this work does not include any hardcoded secrets or passwords
- [X] I have made corresponding changes to the documentation
- [X] I have provided details on how I have tested my code
- [X] I have referenced the ticket number above
- [X] I have provided a description of the ticket

### CODE REVIEW

**Comment by Yakitrak** [comment]
Changes look good but the crypto.js tests are failing on the pipeline. I believe you might need to pass the env variables (to get the encryption key) via the pipeline file to get them to pass.

**Review by BenSurgisonPINS — APPROVED** [review]
lgtm

**Pull request merged**
